### ISSUE TITLE
Allow to not push the tag ?

### ISSUE THREAD

**Issue by dmerejkowsky** [SuperTanker/tbump#16]
For PKGBUILDs, we are not allowed to push tags, so maybe we need:

```toml

[git]
tag_template = "v{new_version}"
message = "..."

[git.push]
tag = false
```
