### ISSUE TITLE
Run hooks after push

### ISSUE THREAD

**Issue by dmerejkowsky** [SuperTanker/tbump#17]
For cargo we have to use `--allow-dirty` in the `tbump.toml`.

Would be better to have something like

```toml
[[hook]]
when = "post_push"
name = "Publish to crates.io"
cmd = "cargo publish"
```
